### ISSUE TITLE
Compatibility issue with Node.js v12.20.0

### ISSUE THREAD

**Issue by DeeCee42** [TA2k/ioBroker.mercedesme#24]
Hi TA2k, all,

I upgraded my iobroker installation this morning to Node & Node.js v12.20.0 (as indicated on the iobroker.Info dashboard).
All the adapters seem to work except for mercedesme, which displays a "websocket error" in the log.

I downgraded back to Node v12.19.1 (using "n") and the error is gone, the mercedesme adapter works fine again.
Interestingly enough, Node.js is still v12.20.0, but anyway ... 

Please check compatibility with Node/Node.js v12.20.0.

Best regards
DeeCee42

P.S. Thanks for upgrading the adapter to handle mercedesme 2020.

**Comment by MCepheus** [comment]
Hello everybody,
I am currently also using Node 12.19.1 and have not made an update yet.
Nevertheless, I have a few "WS errors" in the log file. However, this only occurs very rarely. So far, no more than once a day.
I can't narrow it down any further, but I don't think it's because of the Node update

**Comment by DeeCee42** [comment]
Closing this now. 
ioBroker.mercedesme v0.0.42 is running smoothly with Node.js v12.20.0.
